// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_engraving_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_MuseScore_Engraving)
QT_DECLARE_EXTERN_RESOURCE(engraving_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(engraving_qml_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_MuseScore_Engraving)

class MuseScore_EngravingPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MuseScore_EngravingPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_MuseScore_Engraving)
QT_KEEP_RESOURCE(qmlcache_engraving_qml)
QT_KEEP_RESOURCE(qmake_MuseScore_Engraving)
QT_KEEP_RESOURCE(engraving_qml_raw_qml_0)
QT_KEEP_RESOURCE(engraving_qml_raw_qml_0_extra_qmldirs)
    }
};



#include "engraving_qmlplugin_MuseScore_EngravingPlugin.moc"
