// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_uicomponents_qmlapi)
QT_DECLARE_EXTERN_RESOURCE(qmake_MuseApi_Controls)
QT_DECLARE_EXTERN_RESOURCE(muse_uicomponents_qmlapi_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(muse_uicomponents_qmlapi_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_MuseApi_Controls)

class MuseApi_ControlsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MuseApi_ControlsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_MuseApi_Controls)
QT_KEEP_RESOURCE(qmlcache_muse_uicomponents_qmlapi)
QT_KEEP_RESOURCE(qmake_MuseApi_Controls)
QT_KEEP_RESOURCE(muse_uicomponents_qmlapi_raw_qml_0)
QT_KEEP_RESOURCE(muse_uicomponents_qmlapi_raw_qml_0_extra_qmldirs)
    }
};



#include "muse_uicomponents_qmlapiplugin_MuseApi_ControlsPlugin.moc"
