// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_uicomponents_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_UiComponents)
QT_DECLARE_EXTERN_RESOURCE(muse_uicomponents_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(muse_uicomponents_qml_raw_qml_0_extra_qmldirs)
QT_DECLARE_EXTERN_RESOURCE(muse_uicomponents_qml_raw_qml_1)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_UiComponents)

class Muse_UiComponentsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_UiComponentsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_UiComponents)
QT_KEEP_RESOURCE(qmlcache_muse_uicomponents_qml)
QT_KEEP_RESOURCE(qmake_Muse_UiComponents)
QT_KEEP_RESOURCE(muse_uicomponents_qml_raw_qml_0)
QT_KEEP_RESOURCE(muse_uicomponents_qml_raw_qml_0_extra_qmldirs)
QT_KEEP_RESOURCE(muse_uicomponents_qml_raw_qml_1)
    }
};



#include "muse_uicomponents_qmlplugin_Muse_UiComponentsPlugin.moc"
