/* ============================================== */
/* App                                            */
/* ============================================== */

#define MUSE_APP_NAME_HUMAN_READABLE "MeloPresto Score"
#define MUSE_APP_NAME_MACHINE_READABLE "MeloPrestoScore"

#define MUSE_APP_NAME_HUMAN_READABLE_COMPAT "MuseScore"
#define MUSE_APP_NAME_MACHINE_READABLE_COMPAT "MuseScore"

// TODO: Remove
#define MUSE_APP_NAME "MuseScore"
#define MUSE_APP_TITLE "MeloPresto Score"
// ---

#define MUSE_APP_UNSTABLE 1
/* #undef MUSE_APP_REVISION */
#define MUSE_APP_BUILD_NUMBER "1"
#define MUSE_APP_VERSION "4.7.5"
#define MUSE_APP_VERSION_MAJOR "4"
#define MUSE_APP_VERSION_MINOR "7"
#define MUSE_APP_VERSION_PATCH "5"

/* #undef MUSE_APP_VERSION_LABEL */

/* #undef MUSE_APP_INSTALL_SUFFIX */
#define MUSE_APP_INSTALL_PREFIX "/usr/local"
#define MUSE_APP_INSTALL_NAME "Contents/Resources/"

/* #undef WIN_PORTABLE */

/* ============================================== */
/* Qt Subsystem                                   */
/* ============================================== */
#define QT_QPROCESS_SUPPORTED 1
#define QT_CONCURRENT_SUPPORTED 1

/* ============================================== */
/* Enviropment                                    */
/* ============================================== */
/* #undef MUSE_CONFIGURATION_IS_WEB */
#define MUSE_THREADS_SUPPORT 1
/* #undef MUSE_MULTICONTEXT_WIP */

/* ============================================== */
/* Modules                                        */
/* ============================================== */

#define MUSE_MODULE_ACCESSIBILITY 1
#define MUSE_MODULE_ACCESSIBILITY_TESTS 1
#define MUSE_MODULE_ACCESSIBILITY_API 1

#define MUSE_MODULE_ACTIONS 1
#define MUSE_MODULE_ACTIONS_TESTS 1
#define MUSE_MODULE_ACTIONS_API 1

#define MUSE_MODULE_AUDIO 1
#define MUSE_MODULE_AUDIO_TESTS 1
#define MUSE_MODULE_AUDIO_API 1
/* #undef MUSE_MODULE_AUDIO_ASIO */
/* #undef MUSE_MODULE_AUDIO_PIPEWIRE */
/* #undef MUSE_MODULE_AUDIO_JACK */
#define MUSE_MODULE_AUDIO_EXPORT 1

#define MUSE_MODULE_AUDIO_WORKER_MODE 1
#define MUSE_MODULE_AUDIO_DRIVER_MODE 2
#define MUSE_MODULE_AUDIO_WORKERRPC_MODE 3
#define MUSE_MODULE_AUDIO_WORKMODE 3

#define MUSE_MODULE_AUDIOPLUGINS 1

#define MUSE_MODULE_AUTOBOT 1
#define MUSE_MODULE_AUTOBOT_TESTS 1
#define MUSE_MODULE_AUTOBOT_API 1

#define MUSE_MODULE_CLOUD 1
#define MUSE_MODULE_CLOUD_TESTS 1
#define MUSE_MODULE_CLOUD_API 1

#define MUSE_MODULE_DIAGNOSTICS 1
#define MUSE_MODULE_DIAGNOSTICS_TESTS 1
#define MUSE_MODULE_DIAGNOSTICS_API 1
/* #undef MUSE_MODULE_DIAGNOSTICS_CRASHPAD_CLIENT */

#define MUSE_MODULE_DOCKWINDOW 1
#define MUSE_MODULE_DOCKWINDOW_TESTS 1
#define MUSE_MODULE_DOCKWINDOW_API 1

#define MUSE_MODULE_DRAW 1
#define MUSE_MODULE_DRAW_TESTS 1
#define MUSE_MODULE_DRAW_API 1
#define MUSE_MODULE_DRAW_USE_QTFONTMETRICS 1

#define MUSE_MODULE_EXTENSIONS 1
#define MUSE_MODULE_EXTENSIONS_TESTS 1
#define MUSE_MODULE_EXTENSIONS_API 1

#define MUSE_MODULE_GLOBAL 1
#define MUSE_MODULE_GLOBAL_TESTS 1
#define MUSE_MODULE_GLOBAL_API 1

#define MUSE_MODULE_LANGUAGES 1
#define MUSE_MODULE_LANGUAGES_TESTS 1
#define MUSE_MODULE_LANGUAGES_API 1

#define MUSE_MODULE_LEARN 1
#define MUSE_MODULE_LEARN_TESTS 1
#define MUSE_MODULE_LEARN_API 1

#define MUSE_MODULE_MEDIA 1
#define MUSE_MODULE_MEDIA_TESTS 1
#define MUSE_MODULE_MEDIA_API 1

#define MUSE_MODULE_MIDI 1
#define MUSE_MODULE_MIDI_TESTS 1
#define MUSE_MODULE_MIDI_API 1

#define MUSE_MODULE_MIDIREMOTE 1
#define MUSE_MODULE_MIDIREMOTE_TESTS 1
#define MUSE_MODULE_MIDIREMOTE_API 1

#define MUSE_MODULE_MPE 1
#define MUSE_MODULE_MPE_TESTS 1
#define MUSE_MODULE_MPE_API 1

#define MUSE_MODULE_MULTIWINDOWS 1
#define MUSE_MODULE_MULTIWINDOWS_TESTS 1
#define MUSE_MODULE_MULTIWINDOWS_API 1

#define MUSE_MODULE_MUSESAMPLER 1
#define MUSE_MODULE_MUSESAMPLER_TESTS 1
#define MUSE_MODULE_MUSESAMPLER_API 1
/* #undef MUSE_MODULE_MUSESAMPLER_LOAD_IN_DEBUG */

#define MUSE_MODULE_NETWORK 1
#define MUSE_MODULE_NETWORK_TESTS 1
#define MUSE_MODULE_NETWORK_API 1

#define MUSE_MODULE_SHORTCUTS 1
#define MUSE_MODULE_SHORTCUTS_TESTS 1
#define MUSE_MODULE_SHORTCUTS_API 1

#define MUSE_MODULE_TOURS 1
#define MUSE_MODULE_TOURS_TESTS 1
#define MUSE_MODULE_TOURS_API 1

#define MUSE_MODULE_UI 1
#define MUSE_MODULE_UI_TESTS 1
#define MUSE_MODULE_UI_API 1
/* #undef MUSE_MODULE_UI_DISABLE_MODALITY */
#define MUSE_MODULE_UI_SYSTEMDRAG_SUPPORTED 1
#define MUSE_MODULE_UI_SYNCINTERACTIVE_SUPPORTED 1
#define MUSE_MODULE_UI_NAVIGATION_EXCLUDEPROJECT 1

#define MUSE_MODULE_UPDATE 1
#define MUSE_MODULE_UPDATE_TESTS 1
#define MUSE_MODULE_UPDATE_API 1

#define MUSE_MODULE_VST 1
#define MUSE_MODULE_VST_TESTS 1
#define MUSE_MODULE_VST_API 1

#define MUSE_MODULE_WORKSPACE 1
#define MUSE_MODULE_WORKSPACE_TESTS 1
#define MUSE_MODULE_WORKSPACE_API 1

#define MUSE_ENABLE_UNIT_TESTS 1

#define MELO_SCORE_APP_ID "com.melopresto.score"
#define MELO_SCORE_APP_NAME "MeloPresto Score"
#define MELO_SCORE_APP_VERSION "0.0.0"
#define MELO_SCORE_ORGANIZATION "MeloPresto LLC"
#define MELO_SCORE_DOMAIN "melopresto.com"
#define MELO_SCORE_SETTINGS_NAME "MeloPrestoScore"
#define MELO_SCORE_IPC_NAME "com.melopresto.score.local"

#define MELO_SCORE_SUPPRESS_UPSTREAM_PROMOTIONS 1
