// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_braille_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_MuseScore_Braille)
QT_DECLARE_EXTERN_RESOURCE(braille_qml_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_MuseScore_Braille)

class MuseScore_BraillePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MuseScore_BraillePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_MuseScore_Braille)
QT_KEEP_RESOURCE(qmlcache_braille_qml)
QT_KEEP_RESOURCE(qmake_MuseScore_Braille)
QT_KEEP_RESOURCE(braille_qml_raw_qml_0)
    }
};



#include "braille_qmlplugin_MuseScore_BraillePlugin.moc"
