// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_vst_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_Vst)
QT_DECLARE_EXTERN_RESOURCE(muse_vst_qml_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_Vst)

class Muse_VstPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_VstPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_Vst)
QT_KEEP_RESOURCE(qmlcache_muse_vst_qml)
QT_KEEP_RESOURCE(qmake_Muse_Vst)
QT_KEEP_RESOURCE(muse_vst_qml_raw_qml_0)
    }
};



#include "muse_vst_qmlplugin_Muse_VstPlugin.moc"
