// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_midiremote_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_MidiRemote)
QT_DECLARE_EXTERN_RESOURCE(muse_midiremote_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(muse_midiremote_qml_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_MidiRemote)

class Muse_MidiRemotePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_MidiRemotePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_MidiRemote)
QT_KEEP_RESOURCE(qmlcache_muse_midiremote_qml)
QT_KEEP_RESOURCE(qmake_Muse_MidiRemote)
QT_KEEP_RESOURCE(muse_midiremote_qml_raw_qml_0)
QT_KEEP_RESOURCE(muse_midiremote_qml_raw_qml_0_extra_qmldirs)
    }
};



#include "muse_midiremote_qmlplugin_Muse_MidiRemotePlugin.moc"
