// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_legacytreeview_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_UiComponents_LegacyTreeView)
QT_DECLARE_EXTERN_RESOURCE(muse_legacytreeview_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(muse_legacytreeview_qml_raw_res_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_UiComponents_LegacyTreeView)

class Muse_UiComponents_LegacyTreeViewPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_UiComponents_LegacyTreeViewPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_UiComponents_LegacyTreeView)
QT_KEEP_RESOURCE(qmlcache_muse_legacytreeview_qml)
QT_KEEP_RESOURCE(qmake_Muse_UiComponents_LegacyTreeView)
QT_KEEP_RESOURCE(muse_legacytreeview_qml_raw_qml_0)
QT_KEEP_RESOURCE(muse_legacytreeview_qml_raw_res_0)
    }
};



#include "muse_legacytreeview_qmlplugin_Muse_UiComponents_LegacyTreeViewPlugin.moc"
