// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_multiwindows_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_MultiWindows)
QT_DECLARE_EXTERN_RESOURCE(muse_multiwindows_qml_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_MultiWindows)

class Muse_MultiWindowsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_MultiWindowsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_MultiWindows)
QT_KEEP_RESOURCE(qmlcache_muse_multiwindows_qml)
QT_KEEP_RESOURCE(qmake_Muse_MultiWindows)
QT_KEEP_RESOURCE(muse_multiwindows_qml_raw_qml_0)
    }
};



#include "muse_multiwindows_qmlplugin_Muse_MultiWindowsPlugin.moc"
