// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_ui_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_Ui)
QT_DECLARE_EXTERN_RESOURCE(muse_ui_qml_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_Ui)

class Muse_UiPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_UiPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_Ui)
QT_KEEP_RESOURCE(qmlcache_muse_ui_qml)
QT_KEEP_RESOURCE(qmake_Muse_Ui)
QT_KEEP_RESOURCE(muse_ui_qml_raw_qml_0)
    }
};



#include "muse_ui_qmlplugin_Muse_UiPlugin.moc"
