// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_appshell_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_MuseScore_AppShell)
QT_DECLARE_EXTERN_RESOURCE(appshell_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(appshell_qml_raw_res_0)
QT_DECLARE_EXTERN_RESOURCE(appshell_qml_raw_qml_0_extra_qmldirs)
QT_DECLARE_EXTERN_RESOURCE(appshell_qml_raw_qml_1)
QT_DECLARE_EXTERN_RESOURCE(appshell_qml_raw_qml_1_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_MuseScore_AppShell)

class MuseScore_AppShellPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MuseScore_AppShellPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_MuseScore_AppShell)
QT_KEEP_RESOURCE(qmlcache_appshell_qml)
QT_KEEP_RESOURCE(qmake_MuseScore_AppShell)
QT_KEEP_RESOURCE(appshell_qml_raw_qml_0)
QT_KEEP_RESOURCE(appshell_qml_raw_res_0)
QT_KEEP_RESOURCE(appshell_qml_raw_qml_0_extra_qmldirs)
QT_KEEP_RESOURCE(appshell_qml_raw_qml_1)
QT_KEEP_RESOURCE(appshell_qml_raw_qml_1_extra_qmldirs)
    }
};



#include "appshell_qmlplugin_MuseScore_AppShellPlugin.moc"
