// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_palette_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_MuseScore_Palette)
QT_DECLARE_EXTERN_RESOURCE(palette_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(palette_qml_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_MuseScore_Palette)

class MuseScore_PalettePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MuseScore_PalettePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_MuseScore_Palette)
QT_KEEP_RESOURCE(qmlcache_palette_qml)
QT_KEEP_RESOURCE(qmake_MuseScore_Palette)
QT_KEEP_RESOURCE(palette_qml_raw_qml_0)
QT_KEEP_RESOURCE(palette_qml_raw_qml_0_extra_qmldirs)
    }
};



#include "palette_qmlplugin_MuseScore_PalettePlugin.moc"
