// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_learn_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_Learn)
QT_DECLARE_EXTERN_RESOURCE(muse_learn_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(muse_learn_qml_raw_res_0)
QT_DECLARE_EXTERN_RESOURCE(muse_learn_qml_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_Learn)

class Muse_LearnPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_LearnPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_Learn)
QT_KEEP_RESOURCE(qmlcache_muse_learn_qml)
QT_KEEP_RESOURCE(qmake_Muse_Learn)
QT_KEEP_RESOURCE(muse_learn_qml_raw_qml_0)
QT_KEEP_RESOURCE(muse_learn_qml_raw_res_0)
QT_KEEP_RESOURCE(muse_learn_qml_raw_qml_0_extra_qmldirs)
    }
};



#include "muse_learn_qmlplugin_Muse_LearnPlugin.moc"
