# CMake generated Testfile for 
# Source directory: /Users/jim/Developer/MeloPresto/Temp/melopresto-score-claude-naming-residue/src/framework
# Build directory: /Users/jim/Developer/MeloPresto/Temp/melopresto-score-claude-naming-residue/build.naming/src/framework
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("pch")
subdirs("global")
subdirs("ui")
subdirs("uicomponents")
subdirs("ui/qml/Muse/Ui/Dialogs")
subdirs("dockwindow")
subdirs("accessibility")
subdirs("actions")
subdirs("audio")
subdirs("audioplugins")
subdirs("autobot")
subdirs("cloud")
subdirs("diagnostics")
subdirs("draw")
subdirs("midi")
subdirs("midiremote")
subdirs("mpe")
subdirs("musesampler")
subdirs("network")
subdirs("shortcuts")
subdirs("tours")
subdirs("multiwindows")
subdirs("languages")
subdirs("learn")
subdirs("media")
subdirs("extensions")
subdirs("workspace")
subdirs("vst")
subdirs("update")
subdirs("testing/thirdparty/googletest")
subdirs("stubs")
