// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_muse_diagnostics_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_Muse_Diagnostics)
QT_DECLARE_EXTERN_RESOURCE(muse_diagnostics_qml_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Muse_Diagnostics)

class Muse_DiagnosticsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Muse_DiagnosticsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Muse_Diagnostics)
QT_KEEP_RESOURCE(qmlcache_muse_diagnostics_qml)
QT_KEEP_RESOURCE(qmake_Muse_Diagnostics)
QT_KEEP_RESOURCE(muse_diagnostics_qml_raw_qml_0)
    }
};



#include "muse_diagnostics_qmlplugin_Muse_DiagnosticsPlugin.moc"
