// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_playback_qml)
QT_DECLARE_EXTERN_RESOURCE(qmake_MuseScore_Playback)
QT_DECLARE_EXTERN_RESOURCE(playback_qml_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(playback_qml_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_MuseScore_Playback)

class MuseScore_PlaybackPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MuseScore_PlaybackPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_MuseScore_Playback)
QT_KEEP_RESOURCE(qmlcache_playback_qml)
QT_KEEP_RESOURCE(qmake_MuseScore_Playback)
QT_KEEP_RESOURCE(playback_qml_raw_qml_0)
QT_KEEP_RESOURCE(playback_qml_raw_qml_0_extra_qmldirs)
    }
};



#include "playback_qmlplugin_MuseScore_PlaybackPlugin.moc"
